name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - 'main'
  schedule:
  - cron: 0 0 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # php_version: ["7.1", "7.4", "8.1"]
        php_version: ["my-7.1", "my-7.4", "my-8.1"]
        # php_version: ["my-7.1"]
    steps:
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v3
      -
        # https://github.com/marketplace/actions/docker-metadata-action
        name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            yifans/php-workspace
          flavor: |
            suffix=-${{ matrix.php_version }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        # https://github.com/docker/setup-buildx-action
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        # https://github.com/marketplace/actions/build-and-push-docker-images
        name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          file: Dockerfile-${{ matrix.php_version }}
          # platforms: linux/amd64,linux/arm64,linux/386
          push: ${{ (github.repository == 'imzyf/php-workspace-image') && (github.ref == 'refs/heads/main') }}
          tags: ${{ steps.meta.outputs.tags }}

